### ISSUE TITLE
Plexamp question

### ISSUE THREAD

**Issue by matemoln** [snorre-k/musicbox#6] opened 2019-06-05 16:34 UTC
Hi,
Do you have [this issue](https://forums.plex.tv/t/plexamp-rpi-soundcard-exclusive-control/378884) solved in your Plexamp installation?
Thanks for the scripts!

**Comment by snorre-k** [comment] 2019-06-07 05:11
The issue is resolved in general, as an ALSA software mixer is setup in [asound.conf](https://github.com/snorre-k/musicbox/blob/master/scripts/hifiberry/asound.conf) in the HifiBerry [setup](https://github.com/snorre-k/musicbox/tree/master/scripts/hifiberry). The solution is taken from [here](https://support.hifiberry.com/hc/en-us/articles/207397665-Mixing-different-audio-sources).

**Closed as completed** 2019-07-14 16:14 UTC

**Comment by matemoln** [comment] 2019-12-16 19:39
Just got around to do this. Thank you very much! 👍
